services:
  - type: web
    name: discord-key-bot-dashboard
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DISCORD_MONTH_KEY_USERS
        sync: false
    healthCheckPath: /